import axios from "axios";

const userService = {

    fetchUserById(id: number): Promise<User> {
        return new Promise((resolve, reject) => {
            axios
                .get<User>(`/api/users/${id}`, { timeout: 5000 })
                .then(response => {
                    resolve(response.data);
                })
                .catch(err => {
                    reject(err)
                });
        });
    }

};

export {
    userService
};

// Generated by https://quicktype.io

export interface User {
    id: number;
    name: string;
    username: string;
    email: string;
    address: Address;
    phone: string;
    website: string;
    company: Company;
}

interface Address {
    street: string;
    suite: string;
    city: string;
    zipcode: string;
    geo: Geo;
}

interface Geo {
    lat: string;
    lng: string;
}

interface Company {
    name: string;
    catchPhrase: string;
    bs: string;
}
